// Generated by CoffeeScript 1.3.3
(function() {
  var WordBump,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.WordBump = WordBump = (function(_super) {

    __extends(WordBump, _super);

    function WordBump() {
      return WordBump.__super__.constructor.apply(this, arguments);
    }

    Batman.ViewStore.prefix = 'zprojects/batmanjs-demos/001-local-wordbump/views';

    WordBump.controller('app');

    WordBump.model('word');

    WordBump.root('app#index');

    WordBump.route('app', 'app#index');

    WordBump.on('run', function() {
      return typeof console !== "undefined" && console !== null ? console.log("Running ....") : void 0;
    });

    WordBump.on('ready', function() {
      return typeof console !== "undefined" && console !== null ? console.log("WordBump ready for use.") : void 0;
    });

    WordBump.flash = Batman();

    WordBump.flash.accessor({
      get: function(key) {
        return this[key];
      },
      set: function(key, value) {
        return this[key] = value;
      }
    });

    return WordBump;

  })(Batman.App);

}).call(this);
