// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WordBump.AppController = (function(_super) {

    __extends(AppController, _super);

    function AppController() {
      return AppController.__super__.constructor.apply(this, arguments);
    }

    AppController.prototype.routingKey = 'app';

    AppController.prototype.index = function() {
      this.set('wordOne', new WordBump.Word({
        name: 'Ninja',
        rank: 0
      }));
      return this.set('wordTwo', new WordBump.Word({
        name: 'Waffle',
        rank: 0
      }));
    };

    return AppController;

  })(Batman.Controller);

}).call(this);
