// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WordBump.AppController = (function(_super) {

    __extends(AppController, _super);

    function AppController() {
      return AppController.__super__.constructor.apply(this, arguments);
    }

    AppController.prototype.routingKey = 'app';

    AppController.prototype.index = function() {
      return this.set('wordList', this.fillWordList());
    };

    AppController.prototype.bumpUpOne = function() {
      return this.wordOne.set('rank', this.wordOne.get('rank') + 1);
    };

    AppController.prototype.bumpUpTwo = function() {
      return this.wordTwo.set('rank', this.wordTwo.get('rank') + 1);
    };

    AppController.prototype.fillWordList = function() {
      var word, wordList, words, _i, _len;
      wordList = [];
      words = ['waffle', 'batman', 'ninja', 'rock', 'paper', 'tree'];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        wordList.push(new WordBump.Word({
          name: word,
          rank: 0
        }));
      }
      return wordList;
    };

    return AppController;

  })(Batman.Controller);

}).call(this);
